In [1]:
import numpy as np

In [2]:
age_data = {
    'household_size_distn': {1: 0.1,
                             2: 0.15,
                             3: 0.3,
                             4: 0.3,
                             5: 0.1,
                             6: 0.025,
                             7: 0.025},
    
    'age_distn': {'0-9': 0.197,
                  '10-19': 0.181,
                  '20-29': 0.135,
                  '30-39': 0.123,
                  '40-49': 0.121,
                  '50-59': 0.084,
                  '60-69': 0.081,
                  '70-79': 0.050,
                  '80+': 0.028}
            }

In [742]:
1.821e6/30

60700.0

30.0

In [743]:
0.1+0.1+np.sum(0.8*np.array([0.07,0.25,0.15,0.04,0.2,0.16,0.13]))
ages_all=np.array(list(household_data['age_distn'].items()))
print(ages_all[:,1].astype(float)*1000)

KeyError: 'age_distn'

In [ ]:
print('0-9',1000*(0.12*0.95+0.16*0.5+0.128*0.5+0.104*0.5))

print('10-19',1000*(0.12*0.05+0.032*1.0+0.16*0.5+0.128*0.5+0.104*0.5))
      
print('20-29',1000*(0.1*0.4+0.1+0.12*0.4+0.16*0.05))

print('30-39',1000*(0.056*0.2+0.12*0.6+0.0322*0.2+0.16*0.4+0.128*0.2+0.104*0.1))

print('40-49',1000*(0.056*0.2+0.12*0.6+0.0322*0.2+0.16*0.4+0.128*0.2+0.104*0.1))

In [726]:
0.05*0.9+0.05*0.1+0.015+0.935*0.28*0.25+0.935*0.28*0.75+0.935*0.18*0.9+0.935*0.18*0.1+0.935*0.19+0.935*0.17+0.935*0.18

1.0

In [1019]:
alone_parma=0.25
couples_without_kids_param=0.85
kids_left_house_p=0.36
old_kids=0.3
two_kids_young=0.28
two_kids_old =0.032

three_kids_young=0.37
three_kids_old =0.1

four_kids_young=0.37
four_kids_old =0.1

one_kid_young_per= 0.7
household_data = {
    #                      [0-9,10-19,20-29,30-39,40-49,50-59,60-69,70-79, 80+]
    'alone': {0.05*0.9:[[],[0,0,2*alone_parma/3,1*alone_parma/3,0,0*(1-alone_parma)/8,3*(1-alone_parma)/8,2*(1-alone_parma)/8,3*(1-alone_parma)/8]]},
    'students_app': {0.05*0.1:[[],[0,0.2,0.8,0,0,0,0,0,0]]},
    'soldier':{0.015:[[],[0.0,0.5,0.5,0,0,0,0,0,0]]},
    'couples_without_kids':  {0.935*0.28*0.25:[[],[0,0,couples_without_kids_param,1-couples_without_kids_param,0,0,0,0,0]]},
    'couples_kids_left_the_house':{0.935*0.28*0.75:[[],[0,0,0,0,0,kids_left_house_p,16*(1-kids_left_house_p)/30,10*(1-kids_left_house_p)/30,4*(1-kids_left_house_p)/30]]},
    'couples_with_one_young_kid':{0.935*0.18*0.9:[[0.7,0.3],[0,0,one_kid_young_per,1-one_kid_young_per,0,0,0,0,0]]},
    'couples_with_one_old_kid':{0.935*0.18*0.1:[[0,0.7,0.3],[0,0.0,0.0,old_kids,1-old_kids,0,0,0,0]]},
    'couples_with_two_kid':{0.935*0.19:[[0.45,0.45,0.1],[0,0,0.05,two_kids_young,1-two_kids_young-two_kids_old,two_kids_old,0,0,0]]},
    'couples_with_three_kid':{0.935*0.17:[[0.45,0.45,0.1],[0,0,0.05,three_kids_young,1-three_kids_old-three_kids_young,three_kids_old,0,0,0]]},
    'couples_with_four_kid_pluse':{0.935*0.18:[[0.45,0.45,0.1],[0,0,0.05,three_kids_young,1-three_kids_old-three_kids_young,three_kids_old,0,0,0]]},
            }

In [1044]:
alone_parma=0.2
couples_without_kids_param=0.8
kids_left_house_p=0.36
old_kids=0.4
two_kids_young=0.28
two_kids_old =0.032

three_kids_young=0.37
three_kids_old =0.2

four_kids_young=0.37
four_kids_old =0.2

one_kid_young_per= 0.7

household_data = {
    #                      [0-9,10-19,20-29,30-39,40-49,50-59,60-69,70-79, 80+]
    'alone': (0.05*0.9,[],[0,0,1*alone_parma/4,2*alone_parma/4,1*alone_parma/4,0*(1-alone_parma)/8,3*(1-alone_parma)/8,2.5*(1-alone_parma)/8,2.5*(1-alone_parma)/8]),
    'students_app': (0.05*0.1,[],[0,0.2,0.8,0,0,0,0,0,0]),
    'soldier':(0.015,[],[0.0,0.7,0.3,0,0,0,0,0,0]),
    'couples_without_kids': (0.935*0.28*0.25,[],[0,0,couples_without_kids_param,1-couples_without_kids_param,0,0,0,0,0]),
    'couples_kids_left_the_house':(0.935*0.28*0.75,[],[0,0,0,0,0,kids_left_house_p,16*(1-kids_left_house_p)/30,10*(1-kids_left_house_p)/30,4*(1-kids_left_house_p)/30]),
    'couples_with_one_young_kid':(0.935*0.18*0.8,[0.7,0.3],[0,0,one_kid_young_per,1-one_kid_young_per,0,0,0,0,0]),
    'couples_with_one_old_kid':(0.935*0.18*0.2,[0,0.8,0.2],[0,0,0,old_kids,1-old_kids,0,0,0,0]),
    'couples_with_two_kid':(0.935*0.19,[0.51,0.46,0.03],[0,0,0.05,two_kids_young,1-two_kids_young-two_kids_old,two_kids_old,0,0,0]),
    'couples_with_three_kid':(0.935*0.2,[0.51,0.44,0.05],[0,0,0.05,three_kids_young,1-three_kids_old-three_kids_young,three_kids_old,0,0,0]),
    'couples_with_four_kid_pluse':(0.935*0.15,[0.51,0.44,0.05],[0,0,0.05,three_kids_young,1-three_kids_old-three_kids_young,three_kids_old,0,0,0]),
            }

In [1045]:
Count = {
    'alone': [],
    'students_app': [],
    'soldier' : [] ,
    'couples_without_kids': [],
    'couples_kids_left_the_house': [],
    'couples_with_one_young_kid':[],
    'couples_with_one_old_kid':[],
    'couples_with_two_kid':[],
    'couples_with_three_kid':[],
    'couples_with_four_kid_pluse':[],
            }

In [1046]:
A[0][0]

[]

In [1047]:
N=1000000
number_of_people_array= [1,4,4,2,2,3,3,4,5,8]
for num,(key,values) in enumerate(household_data.items()):
    
    precent_group= values[0]
    p_ages_kids=values[1]
    p_ages_parents=values[2]
    
    keys_ages=age_data['age_distn'].keys()
    
    number_of_people=N*precent_group
    num_of_people_in_house=number_of_people_array[num]
    num_parents=2
    num_kids=num_of_people_in_house-num_parents
    
    if num<5:
        choise=np.random.choice(list(keys_ages), p=p_ages_parents,size=int(number_of_people))
        Count[key].append(choise)
        
    elif(num>=5 and num <7):
        print(key)
        kids_amount=int((num_kids/num_of_people_in_house)*number_of_people)
        kids_choise=np.random.choice(list(keys_ages)[:len(p_ages_kids)], p=p_ages_kids,size=kids_amount)
        adults_choise=np.random.choice(list(keys_ages), p=p_ages_parents,size=int(number_of_people-kids_amount))
        Count[key].append(np.array(list(kids_choise)+list(adults_choise)))
    else:
        print(key)
        kids_amount=int((num_kids/num_of_people_in_house)*number_of_people)
        kids_choise=np.random.choice(list(keys_ages)[:len(p_ages_kids)], p=p_ages_kids,size=kids_amount)
        adults_choise=np.random.choice(list(keys_ages)[3:], p=p_ages_parents[3:],size=int(number_of_people-kids_amount))
        Count[key].append(np.array(list(kids_choise)+list(adults_choise)))
        

couples_with_one_young_kid
couples_with_one_old_kid
couples_with_two_kid
couples_with_three_kid
couples_with_four_kid_pluse


In [1048]:
Count_2 = {'0-9': 0,
                  '10-19': 0,
                  '20-29': 0,
                  '30-39': 0,
                  '40-49': 0,
                  '50-59': 0,
                  '60-69': 0,
                  '70-79': 0,
                  '80+': 0
        }
            
for num,(keys,values) in enumerate(Count.items()):
    print(np.array(values).shape)
    for i in np.squeeze(values):
        Count_2[i]+=1

(1, 45000)
(1, 5000)
(1, 15000)
(1, 65450)
(1, 196350)
(1, 134640)
(1, 33660)
(1, 177650)
(1, 187000)
(1, 140250)


In [1049]:
values_all=np.array(list(Count_2.items()))[:,1]

In [1050]:
0.1+0.1+np.sum(0.8*np.array([0.07,0.25,0.15,0.04,0.2,0.16,0.13]))
ages_all=np.array(list(age_data['age_distn'].items()))
number_all=ages_all[:,1].astype(float)*1000000
number_all

array([197000., 181000., 135000., 123000., 121000.,  84000.,  81000.,
        50000.,  28000.])

In [1051]:
(((values_all.astype(int)-number_all)/number_all)*100).astype(int)

array([-4, -5,  5, -3,  2, 13,  0,  6,  0])

In [1052]:
(((values_all.astype(int)-number_all)/number_all)*100).astype(int)

array([-4, -5,  5, -3,  2, 13,  0,  6,  0])

In [ ]:
alone (0.1):
0.4 : 25-29 
0.6 : 60+ 
alone_with_others (0.1):
1: 20-29

couples_without_kids (0.056)
20-29 : 0.8
30-39 : 0.2
    
couples_kids_left_the_house (0.2)
50-59:0.5 
60-69:0.9
70-79:0.9
80+:0.9

couples_with_one_young_kid(0.12)
'20-29': 0.4
'30-39': 0.6
'0-9': 0.95
'10-19': 0.05
    
couples_with_old_kid(0.032)
'30-39': 0.2
'40-49': 0.8

'10-19': 1.0

couples_with_two_kid(0.16)
'20-29': 0.05
'30-39': 0.4
'40-49': 0.5
'50-59': 0.05

'0-9': 0.5
'10-19': 0.5
    
couples_with_three_kid(0.128)

'30-39': 0.2
'40-49': 0.4
'50-59': 0.4

'0-9': 0.5
'10-19': 0.5 

couples_with_four_kid_pluse(0.104)
'30-39': 0.1
'40-49': 0.5
'50-59': 0.4
'0-9': 0.5
'10-19': 0.5 